### ISSUE TITLE
edits

### ISSUE THREAD

**Issue by jaclyncleary** [grinnellm/Reports#7]
**SoG** 

- Figure 4 - there was a test set in the Fraser River (Section 291) in the latest draft. I asked Ashley to take a look and she fixed the latitude so it now correctly appears in Sec 173 (near Pylades Is).

- Figure 5 legend: sample type- add "Seine roe" (not just roe)

- SoG data collection program. Edit text, fourth bullet:  Divers with the A-Tlegay Fisheries Society surveyed 5 days... and this sentence:
DFO mentored divers from the A-Tlegay Fisheries Society on the spawn survey protocol in 2017 and 2019; in 2021, these
divers surveyed spawn through a contract with the DFO.

**PRD**
General observations - "Overall length of spawn was below average" - please change to "Perception of overall length of spawn is that it was below average" (Table 9 shows length is above average)

**WCVI**: Tables 12, 13,: removes bottom "Total" rows

All:
"Number of spawns" figure -eg, SoG Figure 12: can we change the yaxis to auto scale? It's hard to pull recent info from 2010s and 2020s

**Comment by grinnellm** [comment]
Oops, just saw this issue @jaclyncleary. Not sure why I wasn't notified? Anyway I just fixed them all except the last one re "Number of spawns". If I set the y-axis scale to vary for each panel, the panels get pretty cluttered (below).  Not sure that's any better? Another option might be to calculate the density instead of number of spawns, which would sum to 1 for each panel. But that wouldn't help give the number of spawns.
![SpawnTiming](https://user-images.githubusercontent.com/25674027/127218030-d2a519f0-7cdd-45e7-abe0-5bb4a8e69676.png)

**Comment by grinnellm** [comment]
Maybe this is a bit better? Y-axes same in each row, but varies among rows. I think this is good. SoG:
![SpawnTiming](https://user-images.githubusercontent.com/25674027/127225637-84fe0a05-507d-425c-aaa3-dabf606d51e3.png)

**Comment by jaclyncleary** [comment]
> Maybe this is a bit better? Y-axes same in each row, but varies among rows. I think this is good. SoG:
> ![SpawnTiming](https://user-images.githubusercontent.com/25674027/127225637-84fe0a05-507d-425c-aaa3-dabf606d51e3.png)

this version looks good
